"use client";

import { useEffect, useState } from "react";
import { Header } from "@/components/layout/Header";
import { ResultsView } from "@/components/ResultsView";
import { Sparkles, Info } from "lucide-react";

export default function DemoPage() {
    const [isDemo, setIsDemo] = useState(false);

    useEffect(() => {
        const demoData = {
            "analysis": {
                "whatItIs": "The ChronoSync X1 - A sleek, AI-powered smartwatch that predicts your stress levels before you feel them.",
                "features": ["Stress Prediction AI", "7-Day Sapphire Battery", "Holographic Interface", "Bio-Metric Locking"],
                "targetAudience": "High-performance executives and bio-hackers who value time and mental clarity.",
                "triggers": ["Control", "Exclusivity", "Peace of Mind", "Future-readiness"],
                "painPoints": ["Burnout", "Battery Anxiety", "Information Overload"],
                "valueLevel": "Premium / Luxury Tech"
            },
            "hooks": [
                "Your watch knows you're stressed before you do. Here's how.",
                "Stop reacting to burnout. Start predicting it.",
                "The jewelry of 2025 isn't just gold. It's biological data.",
                "Is your watch actually smart, or just a second phone screen?",
                "POV: You're wearing the last watch you'll ever need to buy."
            ],
            "angles": [
                { "name": "The Bio-Hacker", "description": "Focus on the data precision and stress prediction metrics." },
                { "name": "The Minimalist Exec", "description": "Focus on the design and how it replaces 10 other devices." },
                { "name": "The Gift of Time", "description": "Focus on the long battery life and efficiency gains." }
            ],
            "scripts30": [
                {
                    "title": "The Morning Routine",
                    "script": "[Scene: Fast cuts of a high-end city apartment at dawn. Person waking up.]\n(Voiceover): Your day hasn't even started, but your ChronoSync already knows the 2:00 PM meeting will be your biggest stressor.\n[Scene: Close up of the watch glowing blue.]\n(Voiceover): It adjusts your schedule. It optimizes your biological rhythm. It doesn't just track time—it saves yours.\n[Scene: Executive walking confidently into a boardroom.]\n(Voiceover): ChronoSync X1. Predict the future. Own your day.\n[Scene: Logo with CTA: Link in Bio.]"
                },
                {
                    "title": "The Deep Sleep",
                    "script": "[Scene: Person sleeping, watch glowing softly.]\n(Voiceover): While you rest, it works. Analyzing recovery. Preparing your focus.\n[Scene: Graph showing stress decreasing.]\n(Voiceover): Wake up with a plan, not just an alarm. ChronoSync X1."
                }
            ],
            "scripts15": [
                {
                    "title": "The Bio-Metric Hook",
                    "script": "[Scene: Macro shot of sapphire glass.]\n(Voiceover): 7-day battery. AI-driven stress prediction. Sapphire crystal logic.\n[Scene: Watch on wrist glowing red then green.]\n(Voiceover): Don't just stay on time. Stay ahead of your biology. ChronoSync X1."
                }
            ],
            "ctas": ["Shop the X1 Collection", "Get 20% Off Launch Week", "Pre-order for 2025"],
            "captions": ["The future is on your wrist.", "Stop Burnout Before It Starts.", "7-Day Battery. 0-Day Stress."],
            "voiceoverTone": "Deep, calm, futuristic, premium",
            "videoUrl": "https://cdn.pixabay.com/video/2019/04/23/23011-332213753_tiny.mp4"
        };

        // Inject into localStorage to trick ResultsView
        localStorage.setItem("generatedAd", JSON.stringify(demoData));
        setIsDemo(true);

        return () => {
            // Optional: clean up demo data when leaving
            // localStorage.removeItem("generatedAd");
        };
    }, []);

    if (!isDemo) return null;

    return (
        <div className="flex min-h-screen flex-col bg-background">
            <Header />
            <div className="bg-primary/10 border-b border-primary/20 py-2 px-4 flex items-center justify-center gap-2 text-sm font-medium text-primary">
                <Info className="h-4 w-4" />
                <span>You are currently viewing a Live Demo. These results were generated by Hytec Ad Gen.</span>
                <Sparkles className="h-4 w-4 animate-pulse" />
            </div>
            <main className="flex-1 container mx-auto px-4 py-8">
                <ResultsView />
            </main>
        </div>
    );
}
