import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export default function TermsPage() {
    return (
        <div className="flex min-h-screen flex-col">
            <Header />
            <main className="flex-1 py-20">
                <div className="container mx-auto px-4 md:px-6 max-w-4xl">
                    <h1 className="text-4xl md:text-5xl font-black tracking-tighter uppercase mb-8 border-b border-primary/20 pb-4">
                        Terms of <span className="text-primary italic">Service</span>
                    </h1>

                    <div className="space-y-8 text-muted-foreground leading-relaxed">
                        <section className="space-y-4">
                            <h2 className="text-xl font-bold text-white uppercase tracking-tight">1. Acceptance of Terms</h2>
                            <p>
                                By accessing or using Hytec Ad Gen, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold text-white uppercase tracking-tight">2. Use of Service</h2>
                            <p>
                                Hytec Ad Gen provides AI-powered content generation. You are responsible for the content you generate and must not use the service for:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Creating deceptive or illegal advertising materials</li>
                                <li>Harassment, hate speech, or explicit content generation</li>
                                <li>Violating intellectual property rights of others</li>
                                <li>Automated scraping or stress-testing our infrastructure</li>
                            </ul>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold text-white uppercase tracking-tight">3. Intellectual Property</h2>
                            <p>
                                The scripts and hooks generated by the AI are provided for your use in campaigns. While you own the final generated assets, the underlying platform, logo, and brand "Hytec Ad Gen" remain the exclusive property of Hytec.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold text-white uppercase tracking-tight">4. Payment and Subscriptions</h2>
                            <p>
                                Certain features require a paid subscription via Stripe. All payments are non-refundable unless specified otherwise. We reserve the right to modify pricing with 30 days notice.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold text-white uppercase tracking-tight">5. AI Limitation of Liability</h2>
                            <p>
                                Our AI generates content based on patterns. We do not guarantee the accuracy, truthfulness, or performance (CTR/Sales) of any generated scripts. You should review all AI-generated content before deployment.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-xl font-bold text-white uppercase tracking-tight">6. Termination</h2>
                            <p>
                                We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior toward our staff or systems.
                            </p>
                        </section>

                        <p className="text-sm italic pt-8 border-t border-white/5">
                            Last Updated: February 2026
                        </p>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
